runtime: python27
api_version: 1
threadsafe: yes
service: default

default_expiration: "1s"

handlers:
- url: /app/(.*)
  static_files: \1
  upload: (.*)

- url: /(.*)
  static_files: index.html
  upload: index.html